"use strict";

// 20 Horses with 13 Owners
module.exports = {
  up: (queryInterface, _Sequelize) => {
    return queryInterface.bulkInsert("Horses", [
      {
        name: "TRF Hot Sari Jane",
        barnName: "Sunny",
        sex: "Mare",
        breed: "American Paint Horse",
        color: "Bay",
        description: "White star on forehead",
        chipped: false,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1484438400,
        stallAssignment: 1,
        quarantine: true,
        moveOutDate: null,
        ownerID: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Leo bar Leo",
        barnName: "Leo",
        sex: "Gelding",
        breed: "Quarter Horse",
        color: "Sorrel",
        description: "White blaze and white socks",
        chipped: true,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1470009600,
        stallAssignment: 2,
        quarantine: true,
        moveOutDate: null,
        ownerID: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Lilly of the Valley",
        barnName: "Lilly",
        sex: "Mare",
        breed: "Tennessee Walking Horse",
        color: "Gray",
        description: "Brown left eye and blue right eye",
        chipped: false,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1541030400,
        stallAssignment: 3,
        quarantine: true,
        moveOutDate: null,
        ownerID: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "King Lear",
        barnName: "Lear",
        sex: "Gelding",
        breed: "Thoroughbred",
        color: "Bay",
        description: "Blaze and white socks",
        chipped: false,
        tattooed: true,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1541030400,
        stallAssignment: 4,
        quarantine: true,
        moveOutDate: 1575936000,
        ownerID: 2,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Secretariat",
        barnName: "Big Red",
        sex: "Stallion",
        breed: "Thoroughbred",
        color: "Sorrel",
        description: "White blaze and socks, really fast",
        chipped: true,
        tattooed: true,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1491264000,
        stallAssignment: 5,
        quarantine: true,
        moveOutDate: null,
        ownerID: 3,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "New Sheriff in Town",
        barnName: "Sheriff",
        sex: "Gelding",
        breed: "Thoroughbred",
        color: "Bay",
        description: "White blaze and left rear white sock",
        chipped: false,
        tattooed: true,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1548806400,
        stallAssignment: 6,
        quarantine: true,
        moveOutDate: null,
        ownerID: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Kansas City Grown",
        barnName: "KC",
        sex: "Gelding",
        breed: "Thoroughbred",
        color: "Bay",
        description: "White blaze and 4 white socks",
        chipped: true,
        tattooed: true,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1526428800,
        stallAssignment: 7,
        quarantine: true,
        moveOutDate: null,
        ownerID: 4,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Mineral Country Playboy",
        barnName: "Playboy",
        sex: "Gelding",
        breed: "Morgan",
        color: "Black",
        description: "White star",
        chipped: true,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1491782400,
        stallAssignment: 8,
        quarantine: true,
        moveOutDate: null,
        ownerID: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Feel the Goose Bumps",
        barnName: "Goose",
        sex: "Mare",
        breed: "Friesian",
        color: "Black",
        description: "No markings",
        chipped: true,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1472515200,
        stallAssignment: 9,
        quarantine: true,
        moveOutDate: null,
        ownerID: 5,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Whiskey",
        barnName: "Whiskey",
        sex: "Gelding",
        breed: "Appendix",
        color: "Chestnut",
        description: "White star",
        chipped: false,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1551398400,
        stallAssignment: 10,
        quarantine: true,
        moveOutDate: null,
        ownerID: 6,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Beauty",
        barnName: "Beauty",
        sex: "Mare",
        breed: "Quarter Horse",
        color: "Palomino",
        description: "Large scar on rear left leg",
        chipped: false,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 484438400,
        stallAssignment: 11,
        quarantine: true,
        moveOutDate: null,
        ownerID: 1,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Lizzy",
        barnName: "Lizzy",
        sex: "Mare",
        breed: "Quarter Horse",
        color: "Bay",
        description: "White blaze and socks on front right and back legs",
        chipped: false,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1535760000,
        stallAssignment: 12,
        quarantine: true,
        moveOutDate: null,
        ownerID: 7,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Hot Chili Pepper",
        barnName: "Chili",
        sex: "Gelding",
        breed: "Mustang",
        color: "Buckskin",
        description: "Black dorsal stripe and black tail and mane",
        chipped: false,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1505433600,
        stallAssignment: 13,
        quarantine: true,
        moveOutDate: null,
        ownerID: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Cowboy",
        barnName: "Cowboy",
        sex: "Gelding",
        breed: "Quarter Horse",
        color: "Sorrel",
        description: "White snip and front white socks",
        chipped: false,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1505433600,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1505433600,
        stallAssignment: 14,
        quarantine: true,
        moveOutDate: null,
        ownerID: 8,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Solid Sapphire",
        barnName: "Sam",
        sex: "Gelding",
        breed: "Thoroughbred",
        color: "Gray",
        description: "Dappled with dark gray tail and mane",
        chipped: true,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1471132800,
        stallAssignment: 15,
        quarantine: true,
        moveOutDate: null,
        ownerID: 9,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Calamity Jane",
        barnName: "Jane",
        sex: "Mare",
        breed: "Quarter Horse",
        color: "Red roan",
        description: "No markings",
        chipped: false,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1551312000,
        stallAssignment: 16,
        quarantine: true,
        moveOutDate: null,
        ownerID: 10,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Toby",
        barnName: "Toby",
        sex: "Gelding",
        breed: "Quarter Horse",
        color: "Paint",
        description: "Blue left eye and brown right eye",
        chipped: true,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1552694400,
        stallAssignment: 17,
        quarantine: true,
        moveOutDate: null,
        ownerID: 11,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Ebony",
        barnName: "Ebony",
        sex: "Mare",
        breed: "Tennessee Walking Horse",
        color: "Black",
        description: "White star",
        chipped: true,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1552694400,
        stallAssignment: 18,
        quarantine: true,
        moveOutDate: null,
        ownerID: 11,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Horse of a Different Color",
        barnName: "OshKosh",
        sex: "Gelding",
        breed: "Quarter Horse",
        color: "Leopard Appaloosa",
        description: "Liver-colored spots",
        chipped: false,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1531180800,
        stallAssignment: 19,
        quarantine: true,
        moveOutDate: null,
        ownerID: 12,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Leaves of Autumn",
        barnName: "Autumn",
        sex: "Gelding",
        breed: "Morgan",
        color: "Bay",
        description: "Dappled on back",
        chipped: true,
        tattooed: false,
        vet: "Jeanie Hauser",
        farrier: "Jeff Miller",
        vacDate: 1574208000,
        vacGiven: "Rabies Rhinoflu",
        moveInDate: 1553990400,
        stallAssignment: 20,
        quarantine: true,
        moveOutDate: null,
        ownerID: 13,
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ]);
  },

  down: (queryInterface, _Sequelize) => {
    return queryInterface.bulkDelete("Horses", null, {});
  }
};
